name: Deploy to EC2

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup SSH
      uses: webfactory/ssh-agent@v0.8.0
      with:
        ssh-private-key: ${{ secrets.EC2_SSH_KEY }}

    - name: Deploy and restart
      run: |
        ssh -o StrictHostKeyChecking=no ubuntu@<YOUR_EC2_PUBLIC_IP> << 'EOF'
          cd /var/www/masttec
          git pull origin main

          # Build frontend
          cd frontend
          npm install
          npm run build

          # Start or restart backend
          cd ../backend
          npm install
          pm2 restart masttec-backend || pm2 start index.js --name masttec-backend
        EOF
